# Generated by Django 4.0.3 on 2022-03-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruits', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
    ]
